aws-solutions-library-samples/data-lakes-on-aws

sdlf-foundations/nested-stacks/template-kibana.yaml

https://github.com/awslabs/aws-serverless-data-lake-framework/issues/9
Added KMS permissions to SetupCognito Lambda

Major Bug Fix - Kibana SetupCognito Lambda requires KMS permissions

---

sdlf-pipeline/nested-stacks/template-statemachine.yaml
sdlf-pipeline/template.yaml
sdlf-stageA/template.yaml
sdlf-stageB/template.yaml
sdlf-team/nested-stacks/template-iam.yaml

*Issue #, if available:* None
Enable XRay tracing conditionally for the StageA & B state machines

Enable tracing for step functions

---

deploy.sh

*Issue #, if available:* None
Add an example bash function to add template protection subject to the environment

Add template protection function

---

.github/ISSUE_TEMPLATE/become-a-reference-customer.md
README.md

Add new issue template to enable customers to add their organisations name / logo to the read.me page

Update issue templates - add reference permission

---

sdlf-cicd/template-cicd-child-foundations.yaml

#61 
Reduce policy size for CICD child CB role

Reducing size policy

---

thirdparty-scms/bbucket/bitbucket-team-pipelines.yml

fix bitbucket team pipeline when checking repositories

---

sdlf-dataset/template.yaml
sdlf-team/nested-stacks/template-iam.yaml

add security configuration to sdlf-dataset glue crawler

---

sdlf-foundations/nested-stacks/template-cloudtrail.yaml

encrypt cloudtrail logs when using externally-provided bucket

---

sdlf-team/scripts/bootstrap_team.sh
sdlf-utils/ingestion-examples/sqoop/sdlf-team/scripts/bootstrap_team.sh
sdlf-utils/pipeline-examples/event-dataset-dependencies/sdlf-team/scripts/bootstrap_team.sh

fix minor typo

---

sdlf-pipLibrary/AWSDataWrangler/external_layers.json
sdlf-pipLibrary/AWSDataWrangler/external_wheels.json

awswrangler-update

---

sdlf-foundations/nested-stacks/template-kibana.yaml

enable versioning on ELK stack bucket

---

.github/workflows/static-checking.yml

#159 
Run cfn-lint against the repository when opening a new PR.

github action: cfn-lint on new PRs

---

sdlf-monitoring/template.yaml

In SDLF 2.0.0 sdlf-monitoring cannot currently be deployed due to errors in the template.
There will be a bigger refactoring soon but in the meantime, let's keep it in a working state.

Fix sdlf-monitoring template issues

---

sdlf-cicd/template-cicd-domain-roles.yaml

cleanup unnecessary permissions for crossaccount roles

IAM permissions cleanup

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

I'm the current main maintainer of the project, it's better to assign new issues to me these days.

replace jaidisido with cnfait in github issue templates

---

sdlf-pipeline/template.yaml

update sdlf-pipeline to use cloudformation short form syntax (no Fn::)

sdlf-pipeline cloudformation short form syntax

---

sdlf-cicd/nested-stacks/template-cicd-modules-pipelines.yaml
sdlf-cicd/template-cicd-sdlf-repositories.yaml

restore StageA+StageB codepipeline

---

deploy.sh
sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
sdlf-cicd/lambda/team-cicd/src/lambda_function.py
sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-cicd/template-cicd-domain-team-role.yaml
sdlf-cicd/template-cicd-prerequisites.yaml
sdlf-cicd/template-cicd-sdlf-repositories.yaml
sdlf-cicd/template-cicd-team.yaml
sdlf-monitoring/template.yaml
sdlf-pipeline/template.yaml
sdlf-stageA/template.yaml
sdlf-stageB/template.yaml
sdlf-team/template.yaml

General cfn-lint/cfn-nag-driven overhaul.

IAM permissions review & cleanup

---

sdlf-stageB/lambda/stage-b-fetch-metadata/src/lambda_function.py

fix sdlf-stageB handling of glue arguments from dynamodb

fix sdlf-stageB glue arguments from dynamodb

---

deploy.sh
sdlf-cicd/nested-stacks/template-cicd-lambda-layer.yaml
sdlf-cicd/nested-stacks/template-cicd-modules-pipelines.yaml
sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-cicd/template-cicd-sdlf-repositories.yaml
sdlf-cicd/template-cicd-team.yaml
sdlf-cicd/template-lambda-layer.yaml

Deploy the datalakelibrary lambda layer with cloudformation instead of using the awscli.

deploy datalakelibrary using cloudformation

---

CONTRIBUTING.md
README.md
deploy.sh
docs/source/conf.py
docs/source/index.rst
sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
sdlf-cicd/lambda/team-cicd/src/lambda_function.py
sdlf-cicd/nested-stacks/template-cicd-modules-pipelines.yaml
sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-cicd/template-cicd-domain.yaml
sdlf-cicd/template-cicd-sdlf-repositories.yaml
sdlf-cicd/template-cicd-stage.yaml
sdlf-cicd/template-cicd-team.yaml
sdlf-cicd/template.yaml
sdlf-datalakeLibrary/README.md

Use `main` as the default branch name instead of `master`

use 'main' as the default branch name instead of 'master'

---

sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-team/template.yaml
sdlf-utils/pipeline-examples/event-dataset-dependencies/sdlf-engineering-pipeline/nested-stacks/template-athena.yaml

#207 
Create an Athena workgroup per team

create an athena workgroup per team

---

sdlf-team/template.yaml

sdlf-team: create log groups for datasets/pipelines-dynamodb lambda functions

sdlf-team: log groups for datasets/pipelines-dynamodb lambda functions

---

sdlf-datalakeLibrary/python/datalake_library/interfaces/s3_interface.py
sdlf-stageB/lambda/stage-b-postupdate-metadata/src/lambda_function.py

Following [this discussion](https://github.com/awslabs/aws-serverless-data-lake-framework/discussions/210).

get size and last modified metadata from s3 in a single request

---

sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
sdlf-cicd/lambda/team-cicd/src/lambda_function.py
sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-cicd/template-cicd-domain-team-role.yaml

fix single account workshop/demo setup

---

.github/workflows/static-checking.yml

add job in static-checking github action: black

add job in static-checking github action: black

---

.github/workflows/static-checking.yml

add job in static-checking github action: ruff

add job in static-checking github action: ruff

---

.github/workflows/static-checking.yml

add job in static-checking github action: shellcheck

add job in static-checking github action: shellcheck

---

deploy.sh
pyproject.toml
sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
sdlf-cicd/lambda/stagesrepositories-cicd/src/lambda_function.py
sdlf-cicd/lambda/team-cicd/src/lambda_function.py
sdlf-datalakeLibrary/python/datalake_library/data_quality/schema_validator.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/s3_interface.py
sdlf-datalakeLibrary/python/datalake_library/octagon/event.py
sdlf-datalakeLibrary/python/datalake_library/octagon/metric.py
sdlf-datalakeLibrary/python/datalake_library/octagon/peh.py
sdlf-foundations/lambda/catalog/src/lambda_function.py
sdlf-foundations/lambda/replicate/src/lambda_function.py
sdlf-foundations/template.yaml
sdlf-monitoring/lambda/topic/src/lambda_function.py
sdlf-monitoring/template.yaml
sdlf-stageA/lambda/stage-a-error/src/lambda_function.py
sdlf-stageA/lambda/stage-a-preupdate-metadata/src/lambda_function.py
sdlf-stageA/lambda/stage-a-process-object/src/lambda_function.py
sdlf-stageA/lambda/stage-a-routing/src/lambda_function.py
sdlf-stageB/lambda/stage-b-error/src/lambda_function.py
sdlf-stageB/lambda/stage-b-fetch-metadata/src/lambda_function.py
sdlf-stageB/lambda/stage-b-routing/src/lambda_function.py
sdlf-team/lambda/datasets-dynamodb/src/lambda_function.py
sdlf-team/lambda/pipelines-dynamodb/src/lambda_function.py
validate.sh

fix all static checking findings (black, ruff, shellcheck, cfn-lint)
also a good way to test the latest GitHub workflows!
#220 
#221 
#222 

fix all static checking findings (black, ruff, shellcheck, cfn-lint)

---

.cfn-nag-deny-list.yml
.github/workflows/static-checking.yml
sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
sdlf-cicd/nested-stacks/template-cicd-lambda-layer.yaml
sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-cicd/template-cicd-prerequisites.yaml
sdlf-cicd/template-cicd-sdlf-repositories.yaml
sdlf-foundations/template.yaml
sdlf-monitoring/template.yaml
sdlf-stageA/lambda/stage-a-postupdate-metadata/src/lambda_function.py
validate.sh

Fix all cfn_nag findings. Notably: add access logs bucket in devops account.
Add cfn_nag in GitHub static checking workflow so that it's checked when a pull request is opened/updated. Also regroup black and ruff under a single python job.
Two files are excluded from cfn_nag_scan due to the tool [not supporting fn::foreach](https://github.com/stelligent/cfn_nag/issues/621).

Fix all cfn_nag findings

---

sdlf-datalakeLibrary/python/datalake_library/commons.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/s3_interface.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/sqs_interface.py
sdlf-datalakeLibrary/python/datalake_library/octagon/artifact.py
sdlf-datalakeLibrary/python/datalake_library/octagon/client.py
sdlf-datalakeLibrary/python/datalake_library/octagon/event.py
sdlf-datalakeLibrary/python/datalake_library/octagon/metric.py
sdlf-datalakeLibrary/python/datalake_library/octagon/peh.py
sdlf-datalakeLibrary/python/datalake_library/requirements.txt
sdlf-foundations/lambda/catalog-redrive/src/lambda_function.py
sdlf-monitoring/lambda/topic/src/lambda_function.py
sdlf-stageA/lambda/stage-a-redrive/src/lambda_function.py
sdlf-stageB/lambda/stage-b-redrive/src/lambda_function.py

Remove usage of the DynamoDB boto3 resource, replaced with the boto3 client

refactor: remove usage of boto3 resource

---

sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
sdlf-cicd/nested-stacks/template-cicd-lambda-layer.yaml

see https://github.com/awslabs/aws-serverless-data-lake-framework/pull/226

move the -{env} suffix from layers and transforms too

---

sdlf-foundations/template.yaml
sdlf-stageB/lambda/stage-b-fetch-metadata/src/lambda_function.py
sdlf-stageB/state-machine/stage-b.asl.json
sdlf-stageB/template.yaml

add a job poller for the glue crawler in sdlf-stageB

wait for glue crawler to complete in stageB

---

sdlf-cicd/template-cicd-sdlf-repositories.yaml
sdlf-cicd/template-cicd-team.yaml

*Issue #251*
Add KMS Encryption for CodeCommit repositories

add kms encryption for codecommit repositories

---

.github/workflows/static-checking.yml

*Issue #252 
Changes done
-  Updated GitHub actions/checkout from v3 to v4 the latest
- Updated GitHub actions/setup-python from v4 to v5 the latest

 Update GitHub actions to the latest actions version

---

sdlf-cicd/template-cicd-prerequisites.yaml
sdlf-foundations/template.yaml
sdlf-team/template.yaml

*Issue  #256 *
add policies to retain KMS key aliases on update/delete
add SDLF to KMS keys description

add policies to retain KMS key aliases on update/delete

---

deploy.sh
sdlf-datalakeLibrary/python/datalake_library/interfaces/s3_interface.py
sdlf-foundations/lambda/catalog/src/lambda_function.py

update user agent

---

sdlf-cicd/template-codecommit-pr-check.yaml
sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
sdlf-datalakeLibrary/python/datalake_library/octagon/artifact.py
sdlf-datalakeLibrary/python/datalake_library/octagon/event.py
sdlf-datalakeLibrary/python/datalake_library/octagon/peh.py
sdlf-datalakeLibrary/python/datalake_library/octagon/utils.py
sdlf-foundations/lambda/catalog/src/lambda_function.py
sdlf-foundations/lambda/replicate/src/lambda_function.py

Please add me to the contributors list Name: Mebonia Levan, username: levo-777
modified:   sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/artifact.py
modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/event.py
modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/peh.py
modified:   sdlf-datalakeLibrary/python/datalake_library/octagon/utils.py
modified:   sdlf-foundations/lambda/catalog/src/lambda_function.py
modified:   sdlf-foundations/lambda/replicate/src/lambda_function.py

update now() with timezone alias #271

---

.github/workflows/static-checking.yml
.github/workflows/workshop-deployment.yml
.readthedocs.yml
pyproject.toml
sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
sdlf-cicd/nested-stacks/template-cicd-lambda-layer.yaml
sdlf-cicd/template-cicd-prerequisites.yaml
sdlf-cicd/template-cicd-sdlf-pipelines.yaml
sdlf-cicd/template-codecommit-pr-check.yaml
sdlf-cicd/template-lambda-layer.yaml
sdlf-datalakeLibrary/python/datalake_library/requirements.txt
sdlf-foundations/template.yaml
sdlf-stage-dataquality/template.yaml
sdlf-stageA/template.yaml
sdlf-stageB/template.yaml
sdlf-team/template.yaml

Changed the lambda runtime in all Lambdas
Changed CodeBuild to use Python 12 on Amazon Linux standard 5.0
Upgraded the libraries to latest versions.
For "pytest" I upgraded to the latest 7.x version as upgrading to 8.x may break things and I think a separate PR would be better.
This PR will close issues #268 and #269

Changed all the project to use Python 3.12 -- Lambdas and CodeBuild

---

.github/workflows/static-checking.yml
pyproject.toml
sdlf-cicd/lambda/team-cicd/src/lambda_function.py
validate.sh

Replace black formatter with ruff format

Ruff format

---

sdlf-dataset/template.yaml

Add SSM parameter for Glue Crawler name.

add ssm parameter for Glue Crawler name

---

sdlf-utils/workshop-examples/legislators/deploy.sh

legislators deploy.sh linting

---

sdlf-cicd/template-cicd-domain-team-role.yaml

Add Update* permissions for Glue jobs/connections.

glue job deployer: job/connection Update permissions

---

sdlf-foundations/lambda/replicate/src/lambda_function.py

Use proper DynamoDB JSON structure for items in `sdlf-foundations` replicate lambda. Use f-strings in logger methods while we're at it.

use proper DynamoDB JSON structure for items in sdlf-foundations replicate lambda

---

sdlf-foundations/lambda/catalog/src/lambda_function.py
sdlf-foundations/template.yaml

Use proper DynamoDB JSON structure for items in `sdlf-foundations` catalog lambda.

use proper DynamoDB JSON structure for items in sdlf-foundations catalog lambda

---

sdlf-datalakeLibrary/python/datalake_library/configuration/resource_configs.py
sdlf-foundations/template.yaml
sdlf-stageA/template.yaml
sdlf-stageB/template.yaml
sdlf-team/template.yaml
sdlf-utils/workshop-examples/legislators/deploy.sh

Replace uses of `/SDLF/S3/CentralBucket` with `/SDLF/S3/RawBucket`

replace uses of /SDLF/S3/CentralBucket with /SDLF/S3/RawBucket

---

deploy.sh
sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
sdlf-cicd/template-cicd-sdlf-repositories.gitlab.yaml

Gitlab with curl

---

sdlf-stage-ecsfargate/lambda/routing/src/lambda_function.py
sdlf-stage-ecsfargate/state-machine/stage-ecsfargate.asl.json
sdlf-stage-ecsfargate/template.yaml
sdlf-stage-emrserverless/lambda/routing/src/lambda_function.py
sdlf-stage-emrserverless/state-machine/stage-emrserverless.asl.json
sdlf-stage-emrserverless/template.yaml
sdlf-stage-glue/lambda/routing/src/lambda_function.py
sdlf-stage-glue/state-machine/stage-glue.asl.json
sdlf-stage-glue/template.yaml
sdlf-stage-lambda/lambda/routing/src/lambda_function.py
sdlf-stage-lambda/state-machine/stage-lambda.asl.json
sdlf-stage-lambda/template.yaml

Generic fetching of transform details from DynamoDB in all `sdlf-stage-*` (except dataquality).

[sdlf-stage-*] generic get_transform_details in routing lambda

---

sdlf-stage-ecsfargate/lambda/routing/src/lambda_function.py
sdlf-stage-ecsfargate/state-machine/stage-ecsfargate.asl.json
sdlf-stage-emrserverless/lambda/routing/src/lambda_function.py
sdlf-stage-glue/lambda/routing/src/lambda_function.py
sdlf-stage-glue/state-machine/stage-glue.asl.json
sdlf-stage-lambda/lambda/routing/src/lambda_function.py
sdlf-stage-lambda/state-machine/stage-lambda.asl.json

Put metadata in transform field to avoid name clashes.
Handle decimal metadata for `json.dumps()`.

[sdlf-stage-*] put metadata in transform field, handle decimal metadata

---

sdlf-dataset/.gitignore
sdlf-dataset/template.py
sdlf-foundations/.gitignore
sdlf-foundations/template.py
sdlf-pipeline/.gitignore
sdlf-pipeline/template.py
sdlf-stage-glue/.gitignore
sdlf-stage-glue/template.py
sdlf-stage-lambda/.gitignore
sdlf-stage-lambda/template.py
sdlf-team/.gitignore
sdlf-team/template.py

A CDK version of most SDLF modules. It is not considered stable nor production-ready. Using them is left at an exercise to the reader.

Preview: CDK Python

---

sdlf-stage-glue/template.yaml
sdlf-team/template.py

LakeFormation `DATA_LOCATION_ACCESS` permissions

[sdlf-team][cdk] lakeformation data_location_access permissions

---

sdlf-dataset/template.py

Add missing LakeFormation resources in sdlf-dataset/cdk.

[sdlf-dataset][cdk] lake formation resources

---

sdlf-cicd/lambda/domain-cicd/src/lambda_function.py

Avoid specifying the same set of parameters twice - and avoid issues caused by forgetting multiple places need to be updated.

avoid code duplication in domain-cicd

---

sdlf-team/template.py

Add missing LakeFormation tag and tag permissions in sdlf-team/cdk.

[sdlf-team][cdk] lakeformation tag and tag permissions

---

sdlf-stage-ecsfargate/template.py
sdlf-stage-emrserverless/template.py

[sdlf-stage-emrserverless/ecsfargate] CDK Python

---

sdlf-foundations/template.py
sdlf-team/template.py

Add removal policy to KMS resources, to match the CloudFormation version.

[sdlf-foundations/team][cdk] kms removal policy

---

sdlf-foundations/template.py
sdlf-pipeline/template.py
sdlf-stage-ecsfargate/template.py
sdlf-stage-emrserverless/template.py
sdlf-stage-glue/template.py
sdlf-stage-lambda/template.py
sdlf-team/template.py

Applying the same `DeletionPolicy` we already have in CloudFormation.

[sdlf-*][cdk] set removal policy on stateful resources

---

sdlf-dataset/requirements.txt
sdlf-dataset/template.py
sdlf-foundations/requirements.txt
sdlf-foundations/template.py
sdlf-pipeline/requirements.txt
sdlf-pipeline/template.py
sdlf-stage-ecsfargate/requirements.txt
sdlf-stage-ecsfargate/template.py
sdlf-stage-emrserverless/requirements.txt
sdlf-stage-emrserverless/template.py
sdlf-stage-glue/requirements.txt
sdlf-stage-glue/template.py
sdlf-stage-lambda/requirements.txt
sdlf-stage-lambda/template.py
sdlf-team/requirements.txt
sdlf-team/template.py

Extends `Construct` instead of `Stack`, add `requirements.txt`. The CDK version is still not considered stable, but it is getting better.

[sdlf-*][cdk] extends Construct instead of Stack, add requirements.txt

---

sdlf-team/deployspec.yaml
sdlf-team/modulestack.yaml

#365 
Initial seedfarmer support for `sdlf-team`.

[sdlf-team] seedfarmer support

---

sdlf-dataset/deployspec.yaml
sdlf-dataset/modulestack.yaml

#365 
Initial seedfarmer support for `sdlf-dataset`.

[sdlf-dataset] seedfarmer support

---

sdlf-dataset/modulestack.yaml
sdlf-foundations/modulestack.yaml
sdlf-team/modulestack.yaml

disable w12 check on modulestack where exception is documented

disable w12 check on modulestack where exception is documented

---

sdlf-monitoring/template.yaml

Add CloudWatch log group for Data Firehose transformation lambda.

[sdlf-monitoring] log group for data firehose lambda

---

sdlf-dataset/deployspec.yaml
sdlf-foundations/deployspec.yaml
sdlf-pipeline/deployspec.yaml
sdlf-stage-ecsfargate/deployspec.yaml
sdlf-stage-emrserverless/deployspec.yaml
sdlf-stage-glue/deployspec.yaml
sdlf-stage-lambda/deployspec.yaml
sdlf-team/deployspec.yaml

Use latest version of seed-farmer.

upgrade to seedfarmer 5.0.0 (from 4.0.4)

---

sdlf-cicd/template-cicd-domain-roles.yaml
sdlf-monitoring/lambda/cloudwatchlogs-transformer/src/lambda_function.py
sdlf-monitoring/template.yaml

Improve Firehose Lambda function.

[sdlf-monitoring] firehose lambda: use logging, do not merge log events

---

sdlf-stage-ecsfargate/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-emrserverless/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-glue/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-glue/src/state-machine/stage-glue.asl.json
sdlf-stage-lambda/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-lambda/src/state-machine/stage-lambda.asl.json

[sdlf-stage-*] peh_id is under transform now
[sdlf-stage-glue] proper jsonpaths for crawler input and output

[sdlf-stage-*] peh_id is under transform now

---

sdlf-datalakeLibrary/deployspec.yaml
sdlf-datalakeLibrary/modulestack.yaml

Seed-Farmer support for `sdlf-datalakeLibrary`. `deployspec.yaml` publishes a Lambda layer.

[sdlf-datalakeLibrary] seedfarmer support

---

sdlf-utils/workshop-examples/60-seedfarmer/manifest-sdlf-base.yaml
sdlf-utils/workshop-examples/60-seedfarmer/manifest-sdlf-stages.yaml
sdlf-utils/workshop-examples/60-seedfarmer/manifest-sdlf.yaml

#365 
Manifest examples used in the new "[Deploy SDLF with SeedFarmer](https://catalog.us-east-1.prod.workshops.aws/workshops/501cb14c-91b3-455c-a2a9-d0a21ce68114/en-US/60-seedfarmer)" section of the workshop.

workshop seedfarmer manifest examples

---

sdlf-datalakeLibrary/deployspec.yaml

seedfarmer - make sure setuptools is available

---

sdlf-dataset/deployspec.yaml
sdlf-foundations/deployspec.yaml
sdlf-pipeline/deployspec.yaml
sdlf-stage-ecsfargate/deployspec.yaml
sdlf-stage-emrserverless/deployspec.yaml
sdlf-stage-glue/deployspec.yaml
sdlf-stage-lambda/deployspec.yaml
sdlf-team/deployspec.yaml

Variables weren't populated in the destroy phase - it wasn't deleting any stack as a consequence.

delete cfn stack properly with seedfarmer destroy

---

deploy.sh
sdlf-dataset/pyproject.toml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/lambda/catalog/src/lambda_function.py
sdlf-pipeline/pyproject.toml
sdlf-stage-ecsfargate/pyproject.toml
sdlf-stage-emrserverless/pyproject.toml
sdlf-stage-glue/pyproject.toml
sdlf-stage-lambda/pyproject.toml
sdlf-team/pyproject.toml

update version to 2.5.0-beta.2

---

deploy.sh

avoid substitution issue on macosx

---

sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml

avoid buildspec yaml syntax issues

---

sdlf-cicd/template-cicd-domain-roles.yaml

[sdlf-cicd] lambda:TagResource for event-source-mapping

---

sdlf-cicd/template-cicd-domain-team-role.yaml

[sdlf-cicd] lambda:TagResource for event-source-mapping in team role

---

deploy.sh
sdlf-dataset/pyproject.toml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/lambda/catalog/src/lambda_function.py
sdlf-pipeline/pyproject.toml
sdlf-stage-ecsfargate/pyproject.toml
sdlf-stage-emrserverless/pyproject.toml
sdlf-stage-glue/pyproject.toml
sdlf-stage-lambda/pyproject.toml
sdlf-team/pyproject.toml

update version to 2.5.0

---

deploy.sh
sdlf-dataset/pyproject.toml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/lambda/catalog/src/lambda_function.py
sdlf-pipeline/pyproject.toml
sdlf-stage-ecsfargate/pyproject.toml
sdlf-stage-emrserverless/pyproject.toml
sdlf-stage-glue/pyproject.toml
sdlf-stage-lambda/pyproject.toml
sdlf-team/pyproject.toml

update version to 2.6.0

---

sdlf-utils/workshop-examples/60-seedfarmer/manifest-sdlf-base.yaml

fix datalakeLibrary case in workshop files

---

deploy.sh
sdlf-dataset/pyproject.toml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/lambda/catalog/src/lambda_function.py
sdlf-pipeline/pyproject.toml
sdlf-stage-ecsfargate/pyproject.toml
sdlf-stage-emrserverless/pyproject.toml
sdlf-stage-glue/pyproject.toml
sdlf-stage-lambda/pyproject.toml
sdlf-team/pyproject.toml

update version to 2.7.0-alpha.0

---

sdlf-dataset/src/template.yaml

Add glue database for raw bucket

add glue database for raw bucket

---

sdlf-dataset/src/template.yaml

add glue database for analytics bucket

add glue database for analytics bucket

---

sdlf-dataset/src/template.yaml

`sdlf-dataset` can be deployed without a team - fix a few parameter requirements.

sdlf-dataset can be deployed without a team

---

sdlf-utils/workshop-examples/60-seedfarmer/manifest-sdlf-stages.yaml

workshop examples: add stage- prefix to stages

---

sdlf-dataset/pyproject.toml
sdlf-team/pyproject.toml
sdlf-team/src/team.py

[sdlf-team][sdlf-dataset][cdk] fix imports

---

sdlf-dataset/src/dataset.py
sdlf-foundations/src/foundations.py
sdlf-team/src/team.py

[cdk] Enable key rotation for all KMS keys

---

sdlf-dataset/src/dataset.py

[sdlf-dataset] deployment fixes

---

sdlf-foundations/src/foundations.py

[sdlf-foundations][cdk] CfnDataLakeSettings

---

sdlf-foundations/deployspec.yaml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/app.py

rework sdlf-foundations (cdk) deployment with seedfarmer

---

sdlf-dataset/src/app.py
sdlf-dataset/src/dataset.py

[sdlf-dataset][cdk] data_catalog method to handle raw/stage/analytics catalogs creation

---

sdlf-foundations/src/app.py
sdlf-foundations/src/foundations.py

[sdlf-foundations][cdk] avoid using a hardcoded stack name

---

sdlf-dataset/src/app.py

[sdlf-dataset][cdk] avoid using a hardcoded stack name

---

sdlf-dataset/src/dataset.py
sdlf-foundations/deployspec.yaml
sdlf-foundations/src/foundations.py
sdlf-foundations/src/lambda/catalog/src/lambda_function.py

[sdlf-foundations][cdk] remove pEnvironment parameter
[sdlf-dataset][cdk] remove pEnvironment parameter

[cdk] remove pEnvironment parameter

---

sdlf-dataset/src/dataset.py

[sdlf-dataset][cdk] remove pPipelineDetails parameter
pipeline configuration happens when deploying pipelines directly

[sdlf-dataset][cdk] remove pPipelineDetails parameter

---

sdlf-foundations/src/foundations.py

[sdlf-foundations][cdk] replace octagon with sdlf in dynamo table name

---

sdlf-dataset/src/dataset.py

[sdlf-dataset][cdk] add EMR Security Configuration SSM parameter

---

sdlf-foundations/src/foundations.py
sdlf-foundations/src/lambda/catalog/src/lambda_function.py

[sdlf-foundations][cdk] dynamo table: let cloudformation do the naming

---

sdlf-team/src/team.py

[sdlf-team][cdk] ruff linting

---

sdlf-pipeline/src/pipeline.py
sdlf-stage-ecsfargate/src/ecsfargate.py
sdlf-stage-emrserverless/src/emrserverless.py
sdlf-stage-glue/src/glue.py
sdlf-stage-lambda/src/awslambda.py

[sdlf-pipeline][sdlf-stage-*][cdk] remove sdlf-team dependency

---

sdlf-pipeline/src/pipeline.py
sdlf-stage-ecsfargate/src/ecsfargate.py
sdlf-stage-emrserverless/src/emrserverless.py
sdlf-stage-glue/src/glue.py
sdlf-stage-lambda/src/awslambda.py

Ruff linting for all CDK constructs

---

sdlf-foundations/src/foundations.py

[sdlf-foundations][cdk] ruff formatting

---

sdlf-foundations/src/app.py
sdlf-foundations/src/foundations.py

[sdlf-foundations][cdk] metadata for seedfarmer

---

.gitignore

add seedfarmer.gitmodules to gitignore

---

sdlf-foundations/deployspec.yaml
sdlf-foundations/src/app.py
sdlf-foundations/src/foundations.py

[sdlf-foundations][cdk] ability to provide parameter values without --parameters

---

sdlf-dataset/deployspec.yaml
sdlf-dataset/src/app.py
sdlf-dataset/src/dataset.py

[sdlf-dataset][cdk] ability to provide parameter values without CfnParameter

---

sdlf-pipeline/src/pipeline.py

[sdlf-pipeline][cdk] remove pEnv parameter

---

sdlf-pipeline/deployspec.yaml
sdlf-pipeline/src/pipeline.py

[cdk] rework sdlf-pipeline deployment with seedfarmer

---

sdlf-dataset/src/dataset.yaml
sdlf-foundations/src/foundations.yaml
sdlf-stage-lambda/src/awslambda.yaml
sdlf-team/src/team.yaml

[sdlf-foundations/team/dataset/stage-lambda] cloudformation version without legacy resources

---

sdlf-stage-lambda/src/awslambda.yaml

[sdlf-stage-lambda] remove pEnvironment

---

sdlf-team/src/team.yaml

[sdlf-team] remove unused parameters

---

sdlf-dataset/src/dataset.yaml

[sdlf-dataset] use new ssm parameter format

---

sdlf-stage-glue/src/glue.yaml

[sdlf-stage-glue] cfn without legacy

---

sdlf-team/src/team.py

[sdlf-team][cdk] remove unused parameters

---

sdlf-stage-glue/src/glue.yaml
sdlf-stage-lambda/src/awslambda.yaml

[sdlf-stage-lambda] remove unused ELK parameters
[sdlf-stage-glue] remove unused ELK parameters

[sdlf-stage-lambda/glue] remove unused ELK parameters

---

sdlf-foundations/src/foundations.yaml

[sdlf-foundations] support for 'anycompany' org name

---

sdlf-dataset/src/dataset.yaml

[sdlf-dataset] remove unused parameter

---

sdlf-pipeline/src/pipeline.yaml

[sdlf-pipeline] cfn without legacy

---

sdlf-stage-glue/src/glue.yaml
sdlf-stage-lambda/src/awslambda.yaml

[sdlf-stage-lambda/glue] update input and output ssm parameters

---

sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
sdlf-datalakeLibrary/python/datalake_library/sdlf/__init__.py
sdlf-datalakeLibrary/python/datalake_library/sdlf/config.py
sdlf-datalakeLibrary/python/datalake_library/sdlf/peh.py

[sdlf-datalakeLibrary] support for multiple instances

---

sdlf-stage-lambda/src/awslambda.yaml
sdlf-stage-lambda/src/lambda/error/src/lambda_function.py
sdlf-stage-lambda/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-lambda/src/lambda/process-object/src/lambda_function.py
sdlf-stage-lambda/src/lambda/redrive/src/lambda_function.py
sdlf-stage-lambda/src/lambda/routing/src/lambda_function.py

[sdlf-stage-lambda] pass instance parameters to datalakeLibrary

---

sdlf-stage-glue/src/glue.yaml
sdlf-stage-glue/src/lambda/error/src/lambda_function.py
sdlf-stage-glue/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-glue/src/lambda/routing/src/lambda_function.py
sdlf-stage-glue/src/state-machine/stage-glue.asl.json

[sdlf-stage-glue] pass instance parameters to datalakeLibrary

---

sdlf-utils/workshop-examples/legislators/deploy.sh

[sdlf-utils] reuse artifacts_bucket in legislators deploy script

---

sdlf-team/src/team.yaml

[sdlf-team] update input and output ssm parameters

---

sdlf-utils/workshop-examples/legislators/deploy.sh

[sdlf-utils] use aws cfn deploy instead of create/update-stack

---

sdlf-utils/workshop-examples/legislators/deploy.sh

[sdlf-utils] remove single bucket support in legislators script

---

sdlf-utils/workshop-examples/legislators/deploy.sh

[sdlf-utils] remove unused STAGE_BUCKET from legislators script

---

sdlf-datalakeLibrary/python/datalake_library/sdlf/__init__.py
sdlf-datalakeLibrary/python/datalake_library/sdlf/config.py
sdlf-datalakeLibrary/python/datalake_library/sdlf/peh.py
sdlf-pipeline/src/pipeline.py
sdlf-stage-ecsfargate/src/ecsfargate.py
sdlf-stage-emrserverless/src/emrserverless.py
sdlf-stage-glue/src/glue.py
sdlf-stage-glue/src/lambda/error/src/lambda_function.py
sdlf-stage-glue/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-glue/src/lambda/routing/src/lambda_function.py
sdlf-stage-lambda/src/awslambda.py
sdlf-stage-lambda/src/lambda/error/src/lambda_function.py
sdlf-stage-lambda/src/lambda/postupdate-metadata/src/lambda_function.py
sdlf-stage-lambda/src/lambda/process-object/src/lambda_function.py
sdlf-stage-lambda/src/lambda/redrive/src/lambda_function.py
sdlf-stage-lambda/src/lambda/routing/src/lambda_function.py

ruff formatting/linting

---

sdlf-stage-glue/src/glue.yaml

[sdlf-stage-glue] handling of dataset parameters

---

sdlf-stage-lambda/src/awslambda.yaml

[sdlf-stage-lambda] handling of storage parameters

---

sdlf-stage-glue/src/glue.yaml

[sdlf-stage-glue] handling of storage parameters

---

sdlf-stage-glue/src/glue.yaml
sdlf-stage-glue/src/state-machine/stage-glue.asl.json

[sdlf-stage-glue] glue arguments configurable through cfn parameter

---

sdlf-utils/workshop-examples/legislators/deploy.sh

[sdlf-utils] handle non-existing vpc support ssm parameter in legislators example

---

sdlf-cicd/deploy-generic.sh
sdlf-cicd/manifest-sdlf-base.yaml
sdlf-cicd/manifest-sdlf-stages.yaml
sdlf-cicd/manifest-sdlf.yaml
sdlf-cicd/template-cicd-generic-git.yaml

[sdlf-cicd] simple cicd without codecommit - first take

---

sdlf-foundations/src/lambda/replicate/src/event-create-delete-table.json
sdlf-foundations/src/lambda/replicate/src/event-update-table.json
sdlf-foundations/src/lambda/replicate/src/lambda_function.py

#500 
This reverts commit d37ff61b84ff2c48a8aecf7275cd6afedc362296.

Revert "remove replicate lambda"

---

deploy.sh
sdlf-cicd/deploy-generic.sh
sdlf-datalakeLibrary/python/datalake_library/sdlf/__version__.py
sdlf-dataset/pyproject.toml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/lambda/catalog/src/lambda_function.py
sdlf-pipeline/pyproject.toml
sdlf-stage-ecsfargate/pyproject.toml
sdlf-stage-emrserverless/pyproject.toml
sdlf-stage-glue/pyproject.toml
sdlf-stage-lambda/pyproject.toml
sdlf-team/pyproject.toml

update version to 2.8.0

---

sdlf-cicd/deploy-generic.sh
sdlf-cicd/template-cicd-generic-git.yaml

[sdlf-cicd] generic: loop over list of prefixes instead of duplicating code

---

.cfnlintrc
sdlf-utils/workshop-examples/10-demo/sdlf-workshop/pipeline-main.yaml

add sdlf-cicd generic manifest to cfnlint exclude list

---

sdlf-stage-glue/buildspec.sh
sdlf-stage-lambda/buildspec.sh

[sdlf-stage-lambda/glue] shell script check

---

sdlf-cicd/template-cicd-generic-git.yaml

[sdlf-cicd] simpler retrieval of CICD role

[sdlf-cicd] simpler retrieval of CICD role

---

sdlf-dataset/buildspec.sh
sdlf-foundations/buildspec.sh
sdlf-pipeline/buildspec.sh
sdlf-stage-ecsfargate/buildspec.sh
sdlf-stage-emrserverless/buildspec.sh
sdlf-stage-glue/buildspec.sh
sdlf-stage-lambda/buildspec.sh
sdlf-team/buildspec.sh

[sdlf-*] stack names use deployment type

[sdlf-*] stack names use deployment type

---

sdlf-datalakeLibrary/python/datalake_library/sdlf/__init__.py

[sdlf-datalakeLibrary] update ruff noqa directive

[sdlf-datalakeLibrary] update ruff noqa directive

---

sdlf-utils/workshop-examples/clean-up.sh

[sdlf-utils] workshop cleanup script
see https://catalog.us-east-1.prod.workshops.aws/workshops/501cb14c-91b3-455c-a2a9-d0a21ce68114/en-US/10-demo/600-clean-up

[sdlf-utils] workshop cleanup script

---

sdlf-cicd/template-cicd-generic-git.yaml

[sdlf-cicd] handle workshop workflow

---

sdlf-cicd/deploy-cicd.sh
sdlf-cicd/deploy-role.sh
sdlf-cicd/template-cicd-generic-role.yaml

[sdlf-cicd] handle crossaccount role trust relationship

[sdlf-cicd] handle crossaccount role trust relationship

---

sdlf-cicd/template-cicd-generic-git.yaml

[sdlf-cicd] add missing sdlf-datalakeLibrary construct

---

sdlf-cicd/deploy-cicd.sh
sdlf-utils/workshop-examples/legislators/deploy.sh

[sdlf-utils] better handling of aws profile argument in legislators example

---

README.md
deploy.sh
sdlf-cicd/deploy-cicd.sh
sdlf-cicd/deploy-role.sh
sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/s3_interface.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/sqs_interface.py
sdlf-datalakeLibrary/python/datalake_library/interfaces/states_interface.py
sdlf-datalakeLibrary/python/datalake_library/sdlf/__version__.py
sdlf-dataset/pyproject.toml
sdlf-foundations/pyproject.toml
sdlf-foundations/src/lambda/catalog/src/lambda_function.py
sdlf-pipeline/pyproject.toml
sdlf-stage-ecsfargate/pyproject.toml
sdlf-stage-emrserverless/pyproject.toml
sdlf-stage-glue/pyproject.toml
sdlf-stage-lambda/pyproject.toml
sdlf-team/pyproject.toml

update version to 2.10.0
