aws-solutions-library-samples/data-lakes-on-aws

- sdlf-pipLibrary/AWSDataWrangler/external_layers.json
Build [awswrangler](https://github.com/awslabs/aws-data-wrangler) lambda layer for python3.8.
> Add wrangler38 to external layers

- sdlf-cicd/template-cicd-child-foundations.yaml
- sdlf-foundations/nested-stacks/template-cloudtrail.yaml
- sdlf-foundations/nested-stacks/template-s3.yaml
SECURITY FEATURE: Added bucket policies to enforce s3 in transit encryption (HTTPS only)
"By default, Amazon S3 allows both HTTP and HTTPS requests"
( https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/ )
Bucket whose policies were added or modified:
aws-serverless-data-lake-framework/sdlf-cicd/template-cicd-child-foundations.yaml:
1.a. - rArtifactsBucket. (modified)
aws-serverless-data-lake-framework/sdlf-foundations/nested-stacks/template-cloudtrail.yaml:
2.a. - rTrailBucket (modified)
aws-serverless-data-lake-framework/sdlf-foundations/nested-stacks/template-s3.yaml:
3.a. - rPipelineBucket (new)
3.b. - rCentralBucket (new)
3.c. - rRawBucket (new)
3.d. - rStageBucket (new)
3.e. - rAnalyticsBucket …
> added bucket policies to enforce in transit encryption for s3 buckets

- sdlf-foundations/lambda/catalog/src/lambda_function.py
Previously, this lambda failed because it was able to handle only regular s3 events. For large files that require multipart upload, a different s3 event is generated and this lambda was unable to handle it. Now it is fixed.
*Description of changes:* The new block code checks if there is present a json key called "eventName". If it is present, it means that is a multipart upload and all information is at root event level. Otherwise, it is a regular s3 event and it required to extract information from "record['body']" key.
> Update catalog lambda to handle S3 multipart upload events

- sdlf-foundations/lambda/catalog/src/lambda_function.py
*Description of changes:* When s3 buckets are versioning enabled, and an object is deleted, it generates a DeleteMarkerCreated event. So, in order to support this delete event, the condition is added in this commit.
> Update catalog lambda to support DeleteMarkerCreated event

- sdlf-foundations/nested-stacks/template-kibana.yaml
Add option to set target e-mail for notification as an alias.
"To" e-mail with alias described in here: https://forums.aws.amazon.com/thread.jspa?threadID=85882
Not Available
Add into e-mail regex validation option of "+" character into first part e-mail structure
> Add alias option for target e-mail

- sdlf-utils/ingestion-examples/cdc/dms-task/template.yaml
Resources "rGlueJobLoadIncremental" and "rGlueJobController" had a, what appeared to be, typos of their names. 
Both of them had duplicate "-dms-cdc" sections in their names.
LogGroup from "altb-datalake-dev-intsys-dms-cdc-init-controller" Lambda Function thowing EntityNotFoundException.
Change names for "rGlueJobLoadInitial" and "rGlueJobController"
> Correct typo of Glue Job's name

- sdlf-utils/pipeline-examples/alternative-sdlf-dataset/README.md
- sdlf-utils/pipeline-examples/alternative-sdlf-dataset/deploy.sh
- sdlf-utils/pipeline-examples/alternative-sdlf-dataset/parameters/parameters-legislators.json
- sdlf-utils/pipeline-examples/alternative-sdlf-dataset/tags.json
- sdlf-utils/pipeline-examples/alternative-sdlf-dataset/template.yaml
Issue #, if available:
Description of changes:
Usually you need to deploy not a single dataset but many, so to have a single parameters-$ENV.json file per environment forces you to change the json descriptor each time you need to deploy a new dataset, losing the Jsons that were used to deploy the above datasets.
In the day to day work with the framework, it is common the need to re-deploy the same dataset several times, after a minor change, specially in the dev environment, and rewrite the Json descriptor file each time is not an optimal way to do that.
Instead of having a single json, the present alternative propose to have a folder with one Json file per dataset.
That way the template creates the necessary resources for each dataset from the parameters defined in a …
> Adding deploy mode for datasets

- sdlf-foundations/nested-stacks/template-kibana.yaml
W85 ElasticsearchcDomain should have NodeToNodeEncryptionOptions enabled
Enables node to node enryption
> Enable NodeToNodeEncryptionOptions (CFN_Nag W85)

- sdlf-team/scripts/bootstrap_team.sh
Changes to the template under `sdlf-team/scripts/template-team-repos.yaml` were not updating the _sdlf-crossaccount-role-{ENV}-{TEAM}_ stack.
Updates `sdlf-team/scripts/bootstrap_team.sh` to include the logic for updating the stack.
> Add update stack logic for cross-account team role stack

- sdlf-foundations/nested-stacks/template-glue.yaml
- sdlf-foundations/nested-stacks/template-s3.yaml
- sdlf-foundations/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
- sdlf-team/nested-stacks/template-iam.yaml
- sdlf-utils/pipeline-examples/cloudfront/template.yaml
- sdlf-utils/pipeline-examples/dataset-dependency/stageA/template.yaml
- sdlf-utils/pipeline-examples/manifests/stageA/template.yaml
- sdlf-utils/pipeline-examples/topic-modelling/stageA/template.yaml
- sdlf-utils/pipeline-examples/topic-modelling/stageB/template.yaml
*Issue #, if available:* None
- ensuring Lambda Functions that have CloudWatch log group resources associated with them have both:
- log retention in days set
- the logs are encrypted
- **Note**: this does not cover log groups for Lambda functions that do not have an explicit CloudWatch log group resource. This is primarily because adding an explicit log group resource would likely cause a failure as there would already be an automatically generated one.
> Lambda cloudwatch log encryption retention

- deploy.sh
- sdlf-cicd/template-cicd-shared-foundations.yaml
- sdlf-cicd/template-codecommit-pr-check.yaml
Adding in a CloudFormation template that sets up resources for executing tests when a CodeCommit pull request is raised to certain branches and then sends a pass/fail message to the Activity tab of the relevant pull request.
**Note:** This is a consolidation of the work that was previously achieved here: https://github.com/aws-samples/aws-codecommit-pull-request-aws-codebuild
> Adding in a CloudFormation template that sets up automated testing for CodeCommit Pull Requests

- sdlf-cicd/template-cicd-child-foundations.yaml
- sdlf-foundations/nested-stacks/template-dynamo.yaml
AWS Foundational Security Best Practices v1.0.0 
Control Failed:
[DynamoDB.2] This control checks whether point-in-time recovery (PITR) is enabled for a DynamoDB table
1-Followed remediation instructions for Issue  [DynamoDB.2]  ( https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#dynamodb-2-remediation ) 
2-Added permissions to IAM role sdlf-cicd-codebuild to be able to update the backup settings on the dynamodb tables
> Point-in-time recovery (PITR) enabled for DynamoDB tables

- sdlf-foundations/nested-stacks/template-s3.yaml
FIX to the issue: Get error Unsupported resource ARN Format (Service:Lake formation; status code:400 ; Error Code: InvalidInputException) on rXXBucketLakeFormationS3Registration resources
File sdlf-foundations/nested-stacks/template-s3.yaml
https://github.com/awslabs/aws-serverless-data-lake-framework/issues/76
Fix the ARN format on rXXBucketLakeFormationS3Registration resources
> FIX issue https://github.com/awslabs/aws-serverless-data-lake-framework/issues/76

- deploy.sh
- sdlf-dataset/deploy.sh
- sdlf-foundations/deploy.sh
- sdlf-pipLibrary/build.sh
- sdlf-pipeline/deploy.sh
- sdlf-team/deploy.sh
- sdlf-team/scripts/bootstrap_team.sh
- sdlf-team/scripts/team_check.sh
- thirdparty-scms/ado/functions.sh
- thirdparty-scms/bbucket/functions.sh
- #79 
run `shellcheck` against all sdlf components except sdlf-utils, and fix all findings
> shellcheck

- sdlf-cicd/template-cicd-child-foundations.yaml
These was the error:
Resource handler returned message: "User:
arn:aws:sts::XXXXXXXXXXXX:a ssumed-role/sdlf-cicd-codebuild/AWSCodeBuild-ea3e3133-a258-45f6-b2f0-2300b7891f3 is not authorized to perform: SNS: TagResource on resource:
GERANSESTISSATES-
east-1:033756173027:sdlf-notifications because no identity-based policy allows the SNS:TagResource action (Service: Sns, Status Code: 403, Request ID:
f93cd922-18ec-5223-a32d-854529f9fe0c)"
(RequestToken: affe9cad-404a-9284-2a17-ea95c384f9a, HandlerErrorCode: ÁccessDenied)
The error was fixed manually adding the sns:TagResource to the role: sdlf-cicd-codebuild in IAM services. To avoid future problems is necessary add these permission in the template that create the role.
By submitting this …
> Deploy failed when you deploy a new environment

- sdlf-cicd/template-cicd-child-foundations.yaml
- sdlf-cicd/template-cicd-team-repos.yaml
- sdlf-cicd/template-codecommit-pr-check.yaml
- sdlf-team/nested-stacks/template-cicd.yaml
ubuntu 18.04 to ubuntu 22.04
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
- #111 
> update codebuild image from standard:4.0 to amazonlinux2-x86_64-standard:4.0

- sdlf-team/nested-stacks/template-iam.yaml
- sdlf-utils/ingestion-examples/sqoop/sdlf-team/nested-stacks/template-iam.yaml
- sdlf-utils/pipeline-examples/event-dataset-dependencies/sdlf-team/nested-stacks/template-iam.yaml
- sdlf-utils/pipeline-examples/topic-modelling/template-iam.yaml
> Amazon Elastic Map Reduce (EMR) will soon require permission for the “elasticmapreduce:AddTags” IAM action, which supports tagging when creating an Amazon EMR cluster. Beginning April 24, 2023, this permission will be required in addition to permission for the “elasticmapreduce:RunJobFlow” IAM action, in order to create a cluster with tags.
> add emr tagging permissions

- sdlf-cicd/template-cicd-child-foundations.yaml
#91 
cfn_nag was complaining about rCodeBuildRole and the use of wildcards. This PR fixes that.
Due to the policy getting longer it was necessary to create IAM policies and attach them to the role instead of putting everything in inline policies. This is why the specific profile used to deploy child accounts (./deploy.sh -t) now requires the following permissions in addition to existing ones:
```
iam:GetPolicy
iam:CreatePolicy
iam:DeletePolicy
iam:DetachRolePolicy
iam:ListPolicyVersions
iam:CreatePolicyVersion
iam:DeletePolicyVersion
```
> rework sdlf-cicd rCodeBuildRole IAM role to avoid using wildcards

- sdlf-cicd/template-cicd-child-foundations.yaml
#91 
cfn_nag was complaining about rDataLakeAdminRole and the use of wildcards. This PR fixes that.
> avoid wildcards in sdlf-lakeformation-admin role permissions

- sdlf-foundations/nested-stacks/template-glue.yaml
#91 
cfn_nag was complaining about rRoleLambdaExecutionStep1 and rRoleLambdaExecutionStep2, and their use of wildcards in IAM permissions. This PR fixes that.
> avoid wildcards in data quality lambda permissions

- sdlf-cicd/template-cicd-shared-foundations.yaml
- sdlf-team/scripts/template-team-repos.yaml
#91 
`"*"` is the only possible resource for these actions so there is nothing that can be done to please cfn_nag meaningfully.
> disable cfn_nag W11 on CodeCommit roles

- sdlf-cicd/template-cicd-child-foundations.yaml
- sdlf-foundations/nested-stacks/template-kms.yaml
- sdlf-foundations/nested-stacks/template-s3.yaml
- sdlf-foundations/template.yaml
- sdlf-team/nested-stacks/template-kms.yaml
#137 
By default a service role is created automatically when registering a bucket for the first time. But that doesn't quite work for us at it doesn't do that in CloudFormation: #137
> Create a role for Lake Formation data access

- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
- sdlf-cicd/template-cicd-domain-roles.yaml
When building a new CloudFormation module, store the git commit id of the source in SSM Parameter Store. This commit id is then compared against when building new versions. If the commit id hasn't changed, nothing is built.
> Build CloudFormation module version only when needed

- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-foundations/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
cfn-lint mistakenly complains (E3002) about the Code parameter for CodeCommit. The sam transform takes care of replacing the Code value - so there is no real issue here.
A couple other fixes to cfn-lint findings.
> Improve our cfn-lint posture

- sdlf-cicd/template-codecommit-pr-check.yaml
- sdlf-foundations/template.yaml
- sdlf-pipeline/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
cfn-lint recommends setting explicit values for UpdateReplacePolicy and DeletionPolicy on stateful resources:
> I3011 The default action when replacing/removing a resource is to delete it. Set explicit values for UpdateReplacePolicy / DeletionPolicy on potentially stateful resource: x
> Explicit CloudFormation removal policy

- sdlf-cicd/template-cicd-domain.yaml
- sdlf-cicd/template-cicd-team.yaml
add a build stage before all CloudFormation stages in CodePipeline:
nested stacks can be used easily now, and thus the ability to add tags to nested stacks
tags.json is now expected to exist in sdlf-*-main
> allow tagging infrastructure with stack tags

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-foundations/template.yaml
- sdlf-pipeline/template.yaml
- sdlf-team/template.yaml
#168 
https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/
Create a schedule group per team, then create schedules in this group when required.
The main driver behind this change is to avoid hitting the [fairly low number of EventBridge rules](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-quota.html#eb-limits) that can be created in a single event bus.
> migration to EventBridge Scheduler

- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
CloudFormationManagedUploadInfrastructure now requires s3:PutBucketPublicAccessBlock
> CloudFormationManagedUploadInfrastructure permissions update

- .cfn-nag-deny-list.yml
SPCM is an interesting experiment described here:
https://stelligent.com/2020/03/27/thought-experiment-proposed-complexity-metric-for-iam-policy-documents/
It's a tad too experimental for us. We might enable it back in the future but it is proving challenging to take full advantages of conditions in policies and keep the SCPM low at the same time. This is by design, as described in the article linked above, but we consider conditions important enough to uphold least privilege in SDLF.
> disable cfn_nag W76 SPCM too high

- sdlf-foundations/template.yaml
W12 IAM policy should not allow * resource
suppressed - Condition Applied to restrict access, and the KMS keys do not exist at this stage
W28 Resource found with an explicit name
suppressed for Octagon tables - these names are required for compatibility with Octagon
rDataLakeAdminRole no longer has an explicit name defined - although we should reassess if the role is needed at all really
W58 Lambda functions require permission to write CloudWatch Logs
fixed by reorganising the permissions
W35 S3 access logging
added access-logs bucket
> Fix cfn_nag issues in sdlf-foundations

- deploy.sh
- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
Store the aws-sam-cli zip in s3 when initially setting up SDLF.
This is to avoid hitting GitHub way too many times when building CloudFormation modules. It's not perfect, as new versions of the SAM cli won't be picked up without re-running `deploy.sh`.
CodeArtifact may also be a better fit for this now that it allows uploading generic files such as zip archives. This may happen in the near future.
> store the aws-sam-cli zip in s3 when setting up sdlf

- sdlf-monitoring/template.yaml
Description of changes: sdlf-monitoring: migrate from Elasticsearch 7.10 to OpenSearch 2.5
> sdlf-monitoring: migrate from Elasticsearch 7.10 to OpenSearch 2.5

- sdlf-cicd/template-cicd-sdlf-repositories.yaml
CodeBuild images have both awscli 1 and awscli 2 - remove awscli 1 (via pip) to make sure version 2 is used
> Codebuild awscli version

- .github/workflows/static-checking.yml
- docs/requirements.txt
- pyproject.toml
- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-cicd/template-codecommit-pr-check.yaml
- sdlf-cicd/template-lambda-layer.yaml
- sdlf-datalakeLibrary/python/datalake_library/requirements.txt
- sdlf-foundations/template.yaml
- sdlf-monitoring/template.yaml
- sdlf-stage-dataquality/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
- sdlf-team/template.yaml
- sdlf-utils/ingestion-examples/cdc/dms-replication/template.yaml
- sdlf-utils/pipeline-examples/cloudfront/template.yaml
- sdlf-utils/pipeline-examples/dataset-dependency/stageA/template.yaml
- sdlf-utils/pipeline-examples/manifests/stageA/template.yaml
- sdlf-utils/pipeline-examples/manifests/stageB/template.yaml
- sdlf-utils/pipeline-examples/topic-modelling/pipLibraries/LangDetect/requirements.txt
- sdlf-utils/pipeline-examples/topic-modelling/stageA/template.yaml
- sdlf-utils/pipeline-examples/topic-modelling/stageB/template.yaml
Python 3.11 as default for Lambda functions
> Python 3.11 as default for Lambda functions

- deploy.sh
Older versions do not handle AWS::CodeCommit::Repository Code property with aws cloudformation package.
Remove aws-sam-cli zip archive after upload to s3 to avoid making sdlf-cicd too big to be pushed to codecommit by cloudformation package this only happens in some circumstances, but might as well do this to never have the issue
> Enforce the use of aws-cli >= 2.13.0

- sdlf-stageA/lambda/stage-a-preupdate-metadata/src/lambda_function.py
- sdlf-stageA/state-machine/stage-a.asl.json
- sdlf-stageA/template.yaml
The lambda used in stageA is now configurable through dynamodb using `pPipelineDetails` when deploying a dataset:
```
rLegislators:
Type: awslabs::sdlf::dataset::MODULE
Properties:
pPipelineReference: !Ref pPipelineReference
pTeamName: engineering
pDatasetName: legislators
pPipelineDetails: >-
{
"main": {
"A": {
"lambda_arn": "arn:aws:lambda:us-west-1:111111111111:function:sdlf-engineering-main-custom-a"
},
"B": {
"glue_capacity": {
"NumberOfWorkers": 12,
"WorkerType": "G.1X"
},
"glue_extra_arguments": {
"--enable-auto-scaling": "true"
}
}
}
}
```
> Configurable lambda stageA is now configurable through dynamodb

- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-stageB/lambda/stage-b-fetch-metadata/src/lambda_function.py
The glue job used in stageB is now configurable through dynamodb, using pPipelineDetails when deploying a dataset. See #199 for more details.
> StageB: configurable glue job name through dynamodb

- sdlf-foundations/template.yaml
- sdlf-utils/pipeline-examples/legislators/scripts/legislators-glue-job.yaml
Use KMS for base encryption of S3 buckets. Enable S3 Bucket Key feature as well.
> Use KMS for base encryption of S3 buckets

- sdlf-stage-dataquality/template.yaml
- sdlf-utils/ingestion-examples/cdc/dms-task/template.yaml
- sdlf-utils/pipeline-examples/datalake-workload-management/sdlf-wlm-integration/demo/scripts/legislators-glue-job.yaml
- sdlf-utils/pipeline-examples/glue-jobs-deployer/glue-job.yaml
- sdlf-utils/pipeline-examples/legislators/scripts/legislators-glue-job.yaml
- sdlf-utils/pipeline-examples/manifests/scripts/weather-glue-job.yaml
Update GlueVersion from 2.0 to 4.0, except for pythonshell jobs (upgraded to 3.0) as 4.0 is not supported yet
> update GlueVersion from 2.0 to 4.0

- sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
- sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-cicd/template-cicd-team.yaml
- sdlf-cicd/template-glue-job.yaml
- sdlf-cicd/template-lambda-layer.yaml
- sdlf-team/template.yaml
Set `/SDLF/GlueJobDeployer/Enabled` to true then add python files to `sdlf-main-{domain}-{team}` repository under `transforms-{environment}/{glue_job_name}/{glue_job_name}.py` for it to be automatically deployed.
This is a simplified version of the glue jobs deployer available in sdlf-utils. It may be extended in the future to better match users' use cases.
> add optional glue job deployer feature

- sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
- sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
- sdlf-cicd/lambda/stagesrepositories-cicd/src/lambda_function.py
- sdlf-cicd/lambda/team-cicd/src/lambda_function.py
- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
- sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
- sdlf-cicd/nested-stacks/template-cicd-lambda-layer.yaml
- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-cicd/template-glue-job.yaml
- sdlf-datalakeLibrary/python/datalake_library/configuration/event_configs.py
- sdlf-datalakeLibrary/python/datalake_library/configuration/resource_configs.py
- sdlf-datalakeLibrary/python/datalake_library/data_quality/schema_validator.py
- sdlf-datalakeLibrary/python/datalake_library/interfaces/sqs_interface.py
- sdlf-datalakeLibrary/python/datalake_library/interfaces/states_interface.py
- sdlf-datalakeLibrary/python/datalake_library/octagon/client.py
- sdlf-foundations/lambda/catalog-redrive/src/lambda_function.py
- sdlf-foundations/lambda/catalog/src/lambda_function.py
- sdlf-foundations/lambda/replicate/src/lambda_function.py
- sdlf-foundations/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
- sdlf-team/lambda/datasets-dynamodb/src/lambda_function.py
- sdlf-team/lambda/pipelines-dynamodb/src/lambda_function.py
- sdlf-team/template.yaml
#153 
* vpcs, subnets, vpc endpoints (etc.) deployment is not covered by SDLF - they need provisioning ahead of any SDLF deployment
* regional endpoint urls are passed explicitly in SDLF (boto3 client calls) - `Enable DNS hostnames` and `Enable DNS support`, two VPC attributes, have to be enabled
* `Enable DNS name` has to be enabled on VPC endpoints
Set pEnableVpc to true in both:
* `sdlf-cicd/template-cicd-prerequisites.yaml`
* `sdlf-cicd/template-cicd-domain-roles.yaml`
This will populate the SSM Parameter `/SDLF/VPC/Enabled`. Make sure to provide the following parameters as well (their creation is not handled by SDLF):
* `/SDLF/VPC/VpcId`
* `/SDLF/VPC/SubnetIds`
* `/SDLF/VPC/SecurityGroupIds`
By submitting this pull request, I confirm …
> Optional VPC support for SDLF

- sdlf-datalakeLibrary/python/datalake_library/configuration/resource_configs.py
- sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
- sdlf-foundations/template.yaml
- sdlf-stageB/lambda/stage-b-routing/src/lambda_function.py
- sdlf-team/lambda/datasets-dynamodb/src/lambda_function.py
- sdlf-team/lambda/pipelines-dynamodb/src/lambda_function.py
Restore min/max_items_process feature at the pipeline level.
This used to be at the [dataset level in SDLFv1](https://github.com/awslabs/aws-serverless-data-lake-framework/blob/main/sdlf-stageB/lambda/stage-b-routing/src/lambda_function.py#L37-L38). In SDLFv2 the routing lambda doesn't know the dataset - the SQS queue is shared. This is why it has been moved to the pipeline table.
> restore min/max_items_process feature at the pipeline level

- sdlf-cicd/template-glue-job.yaml
- sdlf-utils/pipeline-examples/legislators/scripts/legislators-glue-job.yaml
#153 
Provide vpc connection to glue jobs in glue-job-deployer, add disable-proxy-v2 to default arguments
> provide vpc connection to glue jobs in glue-job-deployer, add disable-proxy-v2 to default arguments

- sdlf-cicd/lambda/crossaccountteam-cicd/src/lambda_function.py
- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-cicd/template-cicd-team.yaml
`sdlf-cicd-domain-crossaccount-cfn-modules`, `sdlf-cicd-domain-crossaccount-pipeline` and `sdlf-cicd-team-crossaccount-pipeline` have been merged into a single role: `sdlf-cicd-devops-crossaccount-pipeline`
The KMS key and the bucket used to store devops artifacts had invalid policies, as `AWS::Partition` wasn't getting replaced properly and `!Sub` cannot be used in the delimiter part of `!Join`. The fix is not super elegant as conditions need adding for any partition we support. There aren't that many now, thankfully.
The longer term fix is to use KMS grants instead but support in CloudFormation is non-existent:
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/489
and S3 access points but the interaction between CloudFormation and …
> Crossaccount roles simplification

- sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
- sdlf-stageB/lambda/stage-b-postupdate-metadata/src/lambda_function.py
see https://github.com/awslabs/aws-serverless-data-lake-framework/discussions/210 for more information
> add batch capability to updating object metadata in datalakeLibrary

- sdlf-foundations/template.yaml
set lakeformation datalake settings: access control using lakeformation only
note that `MutatePolicy: REPLACE` means pre-existing admins are removed.
> access control using lakeformation only

- sdlf-cicd/template-cicd-team.yaml
The -{env} suffix is unnecessary in team repositories. It makes the deployment workflow more complex (having to edit `-prod` or `-test` files for the other environments). It is still necessary in sdlf-main because that's how you do it by account.
> remove the -{env} suffix from files in team repository

- sdlf-utils/workshop-examples/10-deployment/sdlf-main-datalake-engineering/datasets.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main-datalake-engineering/pipeline-main.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main-datalake-engineering/pipelines.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main-datalake-engineering/tags.json
- sdlf-utils/workshop-examples/10-deployment/sdlf-main/datadomain-datalake-dev.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main/foundations-datalake-dev.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main/tags.json
- sdlf-utils/workshop-examples/10-deployment/sdlf-main/team-datalake-engineering-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main-proserve-iot/datasets.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main-proserve-iot/pipeline-main.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main-proserve-iot/pipeline-singlestage.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main-proserve-iot/pipelines.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main-proserve-iot/tags.json
- sdlf-utils/workshop-examples/20-production/sdlf-main/datadomain-marketing-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/datadomain-proserve-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/foundations-marketing-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/foundations-proserve-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/tags.json
- sdlf-utils/workshop-examples/20-production/sdlf-main/team-marketing-industry-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/team-proserve-iot-dev.yaml
Add files created during the official workshop (sdlf.workshop.aws). People should create them themselves but it is still nice to have them here as reference.
> add workshop examples to sdlf-utils

- sdlf-team/template.yaml
Glue Crawler now requires at least `logs:AssociateKmsKey` for its log group (when encrypted).
> add logs permissions to glue crawler role

- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-foundations/template.yaml
#239 
Renaming the two longest bucket names as the current names are too long when deploying SDLF on region with longer region codes. All regions should be fine following this fix, even when using an organisation name and a data domain name with the maximum number of characters.
> update s3 access logs and artifacts buckets names to avoid length issue

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-dataset/template.yaml
- sdlf-stage-dataquality/template.yaml
- sdlf-team/template.yaml
Create a dedicated LF-Tag per team (Key: `sdlf:team:pTeamName`, Value: `pTeamName`)
Associate this LF-Tag to team datasets
Grant teams Lake Formation permissions (grantable included) on tagged dataset tables
Use all this in sdlf-stage-dataquality as an example to avoid manually granting the required permissions for this stage.
Teams can only associate and grant permissions on their own team LF-Tag.
I would have preferred using `sdlf:team` as key but the `AWS::LakeFormation::Tag` resource requires knowing all values at creation time. The same key cannot be redeclared elsewhere.
> Lake Formation tag (LF-Tag) support for sdlf pipelines

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-team.yaml
#245 
CodePipeline provides a View details button to know more about the issue without having to check the CloudFormation console directly - but it requires DescribeStackEvents.
> add DescribeStackEvents to CodePipeline role permissions (#245)

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-pipeline/template.yaml
- sdlf-team/template.yaml
#165 
The hard limit for number of rules on an event bus is fairly low (2000). SDLF makes extensive use of rules in pipelines, thus hitting the limit quickly. To avoid this, teams now use a dedicated event bus. AWS events are forwarded to it with a rule on the default event bus.
> dedicated event bus per team in child accounts (#165)

- sdlf-dataset/template.yaml
- sdlf-foundations/template.yaml
- sdlf-monitoring/template.yaml
- sdlf-stage-dataquality/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
- sdlf-team/template.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main/foundations-datalake-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/foundations-marketing-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/foundations-proserve-dev.yaml
Rename `pOrganizationName` parameter to `pOrg` to be consistent across all SDLF. This has the added benefits of matching the SSM parameter name (`/SDLF/Misc/pOrg`) and being slightly shorter so helping avoid CloudFormation template length limit.
> rename pOrganizationName parameter to pOrg to be consistent across all SDLF

- .github/workflows/workshop-deployment.yml
this workflow implements part 1 of sdlf.workshop.aws (Deploying SDLF)
When making changes to SDLF, deploying SDLF end-to-end can be quite time-consuming especially if there are issues. Having a GitHub workflow integrates this testing to the development process in an automated way.
I've chosen to follow the workshop steps as it makes a few things easier (files created during the workshop are also available in SDLF's repository) and has the added benefit of making sure the workshop is functional.
This workflow provides access to a configured AWS account. It is intended to run on-demand only, by maintainers, to avoid security issues.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> add on-demand github workflow testing sdlf deployment

- sdlf-team/template.yaml
Make sure lf-tag is created before using it in permissions. CloudFormation may try to create the permissions first, which obviously fails. Using a reference to the tag resource instead of writing its name "manually" avoids this.
> make sure lf-tag is created before using it in permissions

- sdlf-cicd/lambda/team-cicd/src/lambda_function.py
- sdlf-cicd/template-cicd-team-pipeline.yaml
- sdlf-cicd/template-cicd-team-repository.yaml
Fix environment support (a new env would fail when trying to create an already-created team repository).
Also paves the way to not showing irrelevant CodePipeline failures to the user, although that's for a future PR!
> create team repository in a separate stack from team codepipeline

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-monitoring/template.yaml
#158 
sdlf-monitoring can be deployed at the foundations, team or dataset level:
* foundations level: CloudTrail, Logs Forwarding to OpenSearch
* team level: SNS, Storage Lens
* dataset level: SNS, Storage Lens
Admittedly logs forwarding is incomplete right now, and CloudWatch alarms are gone. More work on sdlf-monitoring is upcoming.
> sdlf-monitoring rewrite, add storage lens

- sdlf-cicd/template-cicd-prerequisites.yaml
For some reason CodePipeline starts newly-created pipelines automatically. In SDLF this means they are usually failing, especially because source branches are not available yet: [AWS::CodeCommit::Repository](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codecommit-repository.html) does not allow creating more than one branch through the `Code` parameter, so [when creating pipelines](https://github.com/awslabs/aws-serverless-data-lake-framework/blob/main/sdlf-cicd/nested-stacks/template-cicd-modules-pipelines.yaml) for all environments (dev, test and main branches), `dev` and `test` would fail.
Even if these branches existed the content would need to be relevant to not fail in later stages of the pipelines.
This is confusing for users …
> event rule to stop codepipeline first run (rMain only for now)

- sdlf-cicd/lambda/team-cicd/src/lambda_function.py
- sdlf-cicd/nested-stacks/template-cicd-modules-pipelines.yaml
- sdlf-cicd/template-cicd-sdlf-pipelines.yaml
- sdlf-cicd/template-cicd-team-repository.yaml
Create `sdlf-main-{domain}-{team}` repository with default content and branches.
This allows creating git branches ahead of CodePipelines - then they won't fail so fast, allowing the CodePipeline stopper to kick in (see #261 or 4e290af).
> create sdlf-main-{domain}-{team} repository with default content and branches

- sdlf-cicd/template-cicd-prerequisites.yaml
Update event rule to stop rDomainCodePipeline first run. See also #261.
> update event rule to stop rDomain CodePipeline first run

- sdlf-cicd/lambda/team-cicd/src/lambda_function.py
- sdlf-cicd/template-cicd-sdlf-pipelines.yaml
- add missing permission for team-cicd lambda to remove codecommit approval rules 
- do not fail if there is no kms grant to revoke
- handle crossaccount deletion of the team role stack properly
> fix team removal workflow

- sdlf-foundations/lambda/catalog/src/lambda_function.py
- sdlf-foundations/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
- sdlf-team/template.yaml
- sdlf-utils/workshop-examples/10-deployment/sdlf-main/foundations-datalake-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/foundations-marketing-dev.yaml
- sdlf-utils/workshop-examples/20-production/sdlf-main/foundations-proserve-dev.yaml
Historically SDLF supported two bucket setups:
- a single bucket for the three layers raw/stage/analytics
- one bucket per layer raw/stage/analytics
The three-bucket setup (`pNumBuckets` set to 3) has always been preferred not only in the workshop, but in customer engagements and aws documentation as well (see for example https://aws.amazon.com/blogs/big-data/design-a-data-mesh-architecture-using-aws-lake-formation-and-aws-glue/)
I'm removing the single-bucket setup as this is not best practice - and truth be told, it is not currently functional in SDLF 2.x anyway!
> remove support for single-bucket setup

- sdlf-stage-dataquality/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
`pEntryPoint` is a leftover from previous designs for integrating EventBridge into SDLF pipelines. It is not used at all these days.
> remove unused pEntryPoint parameter in stages

- sdlf-cicd/lambda/team-cicd/src/lambda_function.py
- sdlf-cicd/template-cicd-sdlf-pipelines.yaml
- sdlf-cicd/template-cicd-team-repository.yaml
Parameterize team main repository prefix. `sdlf-main-*` is still the default. This makes it easier to have a side-by-side installation of SDLF v1 and v2, amongst other things.
> parameterize team main repository prefix

- sdlf-foundations/lambda/replicate/src/lambda_function.py
- sdlf-foundations/template.yaml
Avoid using a hardcoded name for the DataSchemas table.
> get dataschemas table name from ssm in replicate lambda

- sdlf-foundations/template.yaml
restrict sdlf-catalog lambda to its dedicated sqs queues
> restrict sdlf-catalog lambda to its dedicated sqs queues

- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-foundations/template.yaml
- sdlf-team/template.yaml
https://aws.amazon.com/about-aws/whats-new/2023/07/aws-cloudformation-deletion-policies-dev-test-cycle/
This makes it much easier to work on SDLF when making updates to foundations and team in particular.
> use RetainExceptOnCreate deletion policy for KMS keys and aliases

- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
Use the stage name instead of a hardcoded `-a` or `-b` to name some of the Lambda functions/state machines in stage A and B. This was already done for some of them so this is a matter of consistency.
> stageA/stageB: replace hardcoded suffix -a/-b with stage name

- sdlf-dataset/template.yaml
- sdlf-utils/workshop-examples/legislators/scripts/legislators-glue-job.yaml
Use SSM parameter to retrieve the Glue security config to use for Glue jobs and crawlers, instead of rebuilding it manually.
> Glue security config SSM

- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
Single role (per stage) for all metadata steps in stageA and stageB.
When deploying hundreds of pipelines AWS limits can be hit fast. Amongst them, the number of IAM roles in a given account (1000 by default, 5000 hard limit). This change makes it a bit harder to hit the limit without reducing security - in effect these "metadata-related" Lambda steps had the same set of permissions.
Also remove unused SQS permissions in stageA.
> single role (per stage) for all metadata steps

- deploy.sh
- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
When running the `crossaccount-cicd-roles` or `devops-account` commands from `deploy.sh`, the user can specify the following flags as `true` to deploy the respective optional features:
- GlueJobDeployer `-g`
- LambdaLayerBuilder `-l`
- Monitoring `-m`
- EnableVpc `-v`
> add flags for optional features to deploy.sh multi-account deployment

- sdlf-cicd/template-cicd-team-pipeline.yaml
#298 
Adding support for nested stacks by adding a packaging step, like we did for pipelines: https://github.com/awslabs/aws-serverless-data-lake-framework/blob/2.2.0/sdlf-cicd/template-cicd-team-pipeline.yaml#L512-L528
> add support for nested stacks in datasets template

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-foundations/template.yaml
- sdlf-stage-dataquality/template.yaml
- sdlf-stageA/template.yaml
- sdlf-stageB/template.yaml
- sdlf-team/template.yaml
#287 
Remove bogus SQS `DeleteMessageBatch`/`SendMessageBatch` permissions. These IAM permissions do not actually exist - batch is covered by `DeleteMessage`/`SendMessage`
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-api-permissions-reference.html
> remove bogus SQS DeleteMessageBatch/SendMessageBatch permissions

- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-foundations/template.yaml
- Enforce TLS on devops s3 access logs bucket
- Update bucket policy for devops artifacts bucket to use a statement similar to the other buckets to enforce TLS. This makes it easier to review.
> Enforce TLS on devops S3 access logs bucket

- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-cicd/template-glue-job.yaml
- sdlf-stageB/lambda/stage-b-fetch-metadata/src/lambda_function.py
- sdlf-team/template.yaml
#312 
Glue Job Deployer: use `/service-role/` path for role
Glue only specify the name, not the full ARN or the name+path, then appends `/service-role/` so service-role has to be used.
`--JOB_NAME` is no longer set. This is now documented as an "internal Glue argument":
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html
> Glue Job Deployer: use /service-role/ path for role

- sdlf-team/lambda/datasets-dynamodb/src/lambda_function.py
- sdlf-team/lambda/pipelines-dynamodb/src/lambda_function.py
Do not set `MaxItems` when paginating. If there is more than 30 pipelines or datasets it is obviously fine!
> do not set MaxItems when paginating

- sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-cicd/template-cicd-team-pipeline.yaml
- sdlf-cicd/template-glue-job.part
- sdlf-cicd/template-glue-job.yaml
#317 
Create a Glue connection per subnet specified in /SDLF/VPC/SubnetIds, and provide the correct value for AvailabilityZone
To do that I had to write more shell than I'd like, but truthfully as long as the Glue Connection resource requires AvailabilityZone this is probably the best way.
> Glue Job Deployer: handle multiple Glue Job Connections, and their AZ

- deploy.sh
- sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
- sdlf-cicd/nested-stacks/template-cicd-modules-pipelines.yaml
- sdlf-cicd/template-cicd-domain.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-cicd/template-cicd-sdlf-pipelines.yaml
- sdlf-cicd/template-cicd-sdlf-repositories.gitlab.yaml
- sdlf-cicd/template-cicd-team-pipeline.yaml
- sdlf-cicd/template-cicd-team-repository.yaml
#270 
Replace CodeCommit entirely with GitLab - all SDLF repositories (components, main and team repositories) can now be hosted on GitLab. This does *not* replace CodeBuild and CodePipeline, GitLab CI/CD is not used.
Creating repositories is done through CloudFormation third-party resource types: https://github.com/aws-ia/cloudformation-gitlab-resource-providers/tree/main/GitLab-Projects-Project
Currently SDLF is very rigid in terms of setup for GitLab, in part due to limitations of the aforementioned resource types.
* Setup a CodeConnection to your GitLab instance.
* Populate `/SDLF/GitLab/CodeConnection` in SSM Parameter Store with the ARN of the CodeConnection.
* Populate `/SDLF/GitLab/Url` in SSM Parameter Store as a secure string …
> sdlf-cicd: support for gitlab as an alternative to codecommit

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-domain-team-role.yaml
- sdlf-cicd/template-cicd-prerequisites.yaml
- sdlf-team/template.yaml
*Issue #272 , if available:*
I saw no one is working on this, so if you don't mind, I want to take a shot.
Replaced deprecated `logs:TagLogGroup` with new permission `logs:TagResource` under these files:
```
./sdlf-team/template.yaml
./sdlf-cicd/template-cicd-domain-roles.yaml
./sdlf-cicd/template-cicd-domain-team-role.yaml
./sdlf-cicd/template-cicd-prerequisites.yaml
```
If you think the above fix looks good to you, I can send out another PR later against master branch to fix in SDLF 1.x.
Please let me know if there is anything else I missed.
> Fix #272: Replace logs:TagLogGroup permission with logs:TagResource

- sdlf-pipeline/template.yaml
- sdlf-stage-lambda/.gitignore
- sdlf-stage-lambda/lambda/error/src/lambda_function.py
- sdlf-stage-lambda/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-lambda/lambda/process-object/src/lambda_function.py
- sdlf-stage-lambda/lambda/redrive/src/lambda_function.py
- sdlf-stage-lambda/lambda/routing/src/lambda_function.py
- sdlf-stage-lambda/state-machine/stage-lambda.asl.json
- sdlf-stage-lambda/template.yaml
#324 
`sdlf-stage-lambda` is a rewrite of `sdlf-stageA`. It can be started from three different triggers:
`sdlf-stageA` is kept and not replaced right away as I want to build some confidence into its usability.
> new stage: sdlf-stage-lambda

- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
It looks like the [latest update](https://github.com/aws-cloudformation/cfn-lint/releases/tag/v1.3.0) from cfn-lint (1.3.0, up from 0.87.7 if we ignore alpha releases) broke cloudformation-cli module submission:
```
Initializing new project
Directory  /codebuild/output/src4169/src/s3/00/module/fragments  Created 
Initialized a new project in /codebuild/output/src4169/src/s3/00/module
=== Unhandled exception ===
Please report this issue to the team.
Issue tracker: github.com/aws-cloudformation/cloudformation-cli/issues
Please include the log file 'rpdk.log'
{
"ETag": "\"604bd20b47c2aa7f201f21e36245d5c4\"",
"ServerSideEncryption": "aws:kms",
"SSEKMSKeyId": "arn:aws:kms:eu-west-1:111111111111:key/fxxx3",
"BucketKeyEnabled": true
}
```
Full `rpdk.log`:
``` …
```
> force use of cfn-lint 0.87.7 since release 1.3.0 break cloudformation-cli

- sdlf-stage-ecsfargate/.gitignore
- sdlf-stage-ecsfargate/lambda/error/src/lambda_function.py
- sdlf-stage-ecsfargate/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-ecsfargate/lambda/redrive/src/lambda_function.py
- sdlf-stage-ecsfargate/lambda/routing/src/lambda_function.py
- sdlf-stage-ecsfargate/state-machine/stage-ecsfargate.asl.json
- sdlf-stage-ecsfargate/template.yaml
Definitely not stable, but a good start anyway: run an ECS Fargate task in a stage. Like #338 it supports three different triggers:
> new stage: sdlf-stage-ecsfargate

- sdlf-stage-emrserverless/.gitignore
- sdlf-stage-emrserverless/lambda/error/src/lambda_function.py
- sdlf-stage-emrserverless/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-emrserverless/lambda/redrive/src/lambda_function.py
- sdlf-stage-emrserverless/lambda/routing/src/lambda_function.py
- sdlf-stage-emrserverless/state-machine/stage-emrserverless.asl.json
- sdlf-stage-emrserverless/template.yaml
- sdlf-team/template.yaml
#309 
Definitely not stable, but a good start anyway: run an EMR Serverless job in a stage. Like #338 and #342 it supports three different triggers:
> new stage: emrserverless

- sdlf-stage-glue/.gitignore
- sdlf-stage-glue/lambda/error/src/lambda_function.py
- sdlf-stage-glue/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-glue/lambda/redrive/src/lambda_function.py
- sdlf-stage-glue/lambda/routing/src/lambda_function.py
- sdlf-stage-glue/state-machine/stage-glue.asl.json
- sdlf-stage-glue/template.yaml
Definitely **not** stable. Aimed at replacing `sdlf-stageb` when stable. Run a Glue job in a stage. Like #338, #342 and #344 it supports three different triggers:
> new stage: sdlf-stage-glue

- sdlf-cicd/nested-stacks/template-cicd-cfn-module.yaml
Related to #341 
It's better to pin to `<1` instead of `0.87.7` to keep receiving minor updates.
> pin cfn-lint to <1 instead of 0.87.7

- sdlf-pipeline/template.yaml
Provide a way to support a third type of trigger:
The other two types already supported are:
> [sdlf-pipeline] support for pipelines with no source event

- deploy.sh
- sdlf-cicd/lambda/domain-cicd/src/lambda_function.py
- sdlf-cicd/template-cicd-sdlf-repositories.gitlab.yaml
- sdlf-cicd/template-cicd-sdlf-repositories.yaml
- sdlf-cicd/template-cicd-team-pipeline.yaml
`stage-lambda` and `stage-glue` are in effect new versions of `stageA` and `stageB`. They will eventually be used in the workshop. Build them by default alongside `stageA` and `stageB` to make things easier for everyone.
Eventually we'd like all stages to be built in the same CodeBuild job (to better manage rate limiting amongst other things) but that's for later.
> build stage-lambda and stage-glue by default

- .gitignore
- docs/constructs/foundations.md
- sdlf-cicd/template-generic-cfn-module.yaml
- sdlf-foundations/deployspec.yaml
- sdlf-foundations/modulestack.yaml
- sdlf-foundations/requirements.txt
Initial seedfarmer support - kind of an alternative to `sdlf-cicd`.
Try to make SDLF play well with seedfarmer, starting with `sdlf-foundations`. Allows building the CloudFormation module, or deploy a stack (from the CDK template) directly.
See for more information:
https://github.com/awslabs/seed-farmer
https://catalog.us-east-1.prod.workshops.aws/workshops/dfd2f6b2-3923-4d79-80bd-7db6c4842122/en-US
Support for building and publishing foundations as a CDK construct is something we're exploring as well.
**This is all in preview state, not fit for production use.**.
> SeedFarmer Support

- sdlf-cicd/template-generic-cfn-module.yaml
- sdlf-foundations/deployspec.yaml
Make `deployspec.yaml` more generic, in order to reuse it almost as-is for other SDLF modules.
> [sdlf-foundations] generic deployspec.yaml

- .github/workflows/static-checking.yml
- validate.sh
related to #341 and #349 
pin cfn-lint to <1 in github workflow
also exclude deployspec.yaml which is not a fully-formed cloudformation template
> pin cfn-lint to <1 in github workflow

- sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
Remove hash from Glue Job CloudFormation reference & script name.
Using a hash forced the glue job to be deleted and recreated - except creation would fail as the deletion only happens after, and the glue job name would still be in-use.
> remove hash from glue job cfn reference & script name

- sdlf-cicd/nested-stacks/template-cicd-glue-job.yaml
- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-cicd/template-cicd-team-pipeline.yaml
Add support for custom templates when using the Glue Job Deployer. It must be called `template.yaml`, in the same directory as the Glue job script, and accept two parameters called `pTeamName` and `pGlueJob`.
> [sdlf-cicd] glue job deployer: support for custom templates

- sdlf-cicd/template-cicd-domain-roles.yaml
- sdlf-monitoring/template.yaml
Use Cloudwatch Logs Account Policy to set up subscription filters on all log groups (forwarding logs to Firehose).
> [sdlf-monitoring] logs account policy for subscription filters

- sdlf-datalakeLibrary/deployspec.yaml
- sdlf-dataset/deployspec.yaml
- sdlf-foundations/deployspec.yaml
- sdlf-pipeline/deployspec.yaml
- sdlf-stage-ecsfargate/deployspec.yaml
- sdlf-stage-emrserverless/deployspec.yaml
- sdlf-stage-glue/deployspec.yaml
- sdlf-stage-lambda/deployspec.yaml
- sdlf-team/deployspec.yaml
Skip `poetry install` in `deployspec.yaml` if we're building a CloudFormation module, not a CDK construct.
> skip poetry install if cfn module

- README.md
- deploy.sh
- sdlf-dataset/pyproject.toml
- sdlf-foundations/pyproject.toml
- sdlf-foundations/src/lambda/catalog/src/lambda_function.py
- sdlf-pipeline/pyproject.toml
- sdlf-stage-ecsfargate/pyproject.toml
- sdlf-stage-emrserverless/pyproject.toml
- sdlf-stage-glue/pyproject.toml
- sdlf-stage-lambda/pyproject.toml
- sdlf-team/pyproject.toml
Update version to `2.5.0-beta.1`.
> update version to 2.5.0-beta.1

- sdlf-foundations/src/template.yaml
- sdlf-team/src/template.yaml
Avoid hardcoding SDLF deployment role names in LakeFormation admin list. They were set to the value `sdlf-cicd` is using, which is not a mandatory module to use SDLF components.
> avoid hardcoding SDLF deployment role name in LakeFormation admin list

- .cfnlintrc
- .github/workflows/static-checking.yml
- validate.sh
seedfarmer manifest files no longer checked by cfn-lint
> use globbing for cfn-lint, set ignore_templates

- sdlf-stage-ecsfargate/src/template.yaml
- sdlf-stage-emrserverless/src/template.yaml
- sdlf-stage-glue/src/template.yaml
- sdlf-stage-lambda/src/template.yaml
`legislators` was used for testing - it doesn't really make sense to keep it as a default value.
> (sdlf-stage-*) don't set default dataset

- sdlf-foundations/src/template.yaml
These tables have not been used in years and are confusing people unnecessarily. This PR is part of a bigger change to remove Octagon-specific code as it is no longer relevant.
> Mark Octagon Configuration, Events, Artifacts, Metrics as legacy

- sdlf-foundations/src/template.yaml
see #400. This PR is part of a bigger change to remove Octagon-specific code as it is no longer relevant.
> mark Octagon-DataSchemas as legacy

- sdlf-dataset/src/template.yaml
add glue crawler for raw bucket
> add glue crawler for raw bucket

- sdlf-dataset/src/template.yaml
add glue crawler for analytics bucket
> add glue crawler for analytics bucket

- sdlf-dataset/src/dataset.py
> [sdlf-dataset][cdk] add peh, manifests tables

- sdlf-foundations/src/foundations.py
> [sdlf-foundations][cdk] data_bucket method to handle raw/stage/analytics buckets creation

- sdlf-dataset/deployspec.yaml
- sdlf-dataset/pyproject.toml
- sdlf-dataset/src/app.py
> rework sdlf-dataset (cdk) deployment with seedfarmer

- sdlf-dataset/src/app.py
- sdlf-dataset/src/dataset.py
> [sdlf-dataset][cdk] ruff linting

- sdlf-dataset/src/app.py
- sdlf-dataset/src/dataset.py
> [sdlf-dataset][cdk] metadata for seedfarmer

- sdlf-dataset/src/dataset.py
- sdlf-pipeline/src/pipeline.py
- sdlf-stage-lambda/deployspec.yaml
- sdlf-stage-lambda/pyproject.toml
- sdlf-stage-lambda/src/app.py
- sdlf-stage-lambda/src/awslambda.py
- sdlf-stage-lambda/src/state-machine/stage-lambda.asl.json
* sdlf-pipeline no longer contains any CfnParameter
* use python 3.11 for cdk (seedfarmer just does not play well with python3.12 currently)
* rework sdlf-stage-lambda deployspec to be more in line with the existing seedfarmer community
* let CloudFormation generate SQS queue names
* follow the new format set in sdlf-foundations and sdlf-dataset for SSM parameters
* remove references to Octagon
* use sdlf-datalakeLibrary lambda layer in stage lambda functions
* pass the event pattern from the user to the event rule properly
still all WIP for now...
> [sdlf-pipeline][sdlf-stage-lambda][cdk] rewrite

- sdlf-stage-glue/src/glue.yaml
> [sdlf-stage-glue] Glue Worker Type configurable through cfn parameter

- sdlf-pipeline/src/pipeline.yaml
- sdlf-stage-glue/src/glue.yaml
[sdlf-pipeline/stage-glue] handling of dataset parameters: `pEventBus`, `pScheduleGroup`, `pInfraKmsKey`
> [sdlf-pipeline/stage-glue] handling of dataset parameters

- sdlf-datalakeLibrary/python/datalake_library/sdlf/config.py
- sdlf-datalakeLibrary/python/datalake_library/sdlf/peh.py
- sdlf-stage-glue/src/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-glue/src/lambda/redrive/src/lambda_function.py
- sdlf-stage-glue/src/lambda/routing/src/lambda_function.py
- sdlf-stage-lambda/src/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-lambda/src/lambda/routing/src/lambda_function.py
[sdlf-stage-glue] use deployment_instance in redrive
[sdlf-stage-glue] remove legacy ObjectMetadata table references
[sdlf-stage-lambda] remove legacy ObjectMetadata table references
[sdlf-datalakeLibrary] remove legacy ObjectMetadata table references
> remove legacy ObjectMetadata table references

- sdlf-team/src/team.yaml
> [sdlf-team] handling of storage parameters

- sdlf-stage-glue/src/glue.yaml
- sdlf-stage-glue/src/state-machine/stage-glue.asl.json
> [sdlf-stage-glue] max items per batch configurable through cfn parameter

- sdlf-utils/workshop-examples/10-demo/sdlf-workshop/dataset-legislators.yaml
- sdlf-utils/workshop-examples/10-demo/sdlf-workshop/foundations-datalake-dev.yaml
- sdlf-utils/workshop-examples/10-demo/sdlf-workshop/pipeline-main.yaml
- sdlf-utils/workshop-examples/10-demo/sdlf-workshop/tags.json
- sdlf-utils/workshop-examples/10-demo/sdlf-workshop/team-datalake-engineering-dev.yaml
> [sdlf-utils] workshop update

- sdlf-cicd/deploy-generic.sh
- sdlf-cicd/template-cicd-generic-git.yaml
* add -V, --version argument
* add -c, --construct argument
* add -r, --region argument
* better handle -p, --profile argument
* update help message
* remove unnecessary credentials config in generic codebuild
* create bootstrap project only once
> [sdlf-cicd] rewrite deploy-generic.sh

- deploy.sh
- sdlf-cicd/deploy-generic.sh
- sdlf-datalakeLibrary/python/datalake_library/interfaces/dynamo_interface.py
- sdlf-datalakeLibrary/python/datalake_library/interfaces/s3_interface.py
- sdlf-datalakeLibrary/python/datalake_library/interfaces/sqs_interface.py
- sdlf-datalakeLibrary/python/datalake_library/interfaces/states_interface.py
- sdlf-datalakeLibrary/python/datalake_library/sdlf/__version__.py
- sdlf-dataset/pyproject.toml
- sdlf-foundations/pyproject.toml
- sdlf-foundations/src/lambda/catalog/src/lambda_function.py
- sdlf-pipeline/pyproject.toml
- sdlf-stage-ecsfargate/pyproject.toml
- sdlf-stage-emrserverless/pyproject.toml
- sdlf-stage-glue/pyproject.toml
- sdlf-stage-lambda/pyproject.toml
- sdlf-team/pyproject.toml
> update version to 2.9.0

- sdlf-cicd/template-cicd-generic-git.yaml
seed-farmer version 6.x breaks the CodeBuild project so we pin it to the previous version for now.
> [sdlf-cicd] generic: pin seed-farmer version

- sdlf-cicd/template-cicd-generic-git.yaml
[sdlf-cicd] use pcodebuildsuffix in artifacts bucket name
> [sdlf-cicd] use pcodebuildsuffix in artifacts bucket name

- sdlf-stage-glue/src/lambda/postupdate-metadata/src/lambda_function.py
- sdlf-stage-glue/src/stageglue.yaml
- sdlf-stage-lambda/src/lambda/postupdate-metadata/src/lambda_function.py
These are temporary changes to ensure the workshop works end-to-end - but they're also the sign the postupdate lambda functions need a rewrite, or more generally the story around failure handling/retry handling (perhaps it is a bad thing to wrap everything in a Try block of type Parallel, as the web console shows the Failure state as the source of the error instead of the actual origin).
> [sdlf-stage-lambda/glue] sync with workshop build
